### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by hack3d** [IT4smart/ManagementCenter-Agent#1]
Translate the "README.md" from german to english.

**Comment by Aminelas** [comment]
Hello,
I would like to translate the "README.md" to english.

**Comment by Aminelas** [comment]
I am going add a new file called README_english.md instead of replacing the file

**Comment by hack3d** [comment]
I will decline the first [PR](https://github.com/IT4smart/ManagementCenter-Agent/pull/3) of you and we take only the second one.

**Comment by hack3d** [comment]
merged PR#2
